export const LocalStorageKey = {
  accessToken: 'lsk_access_token',
  Mobile_Unique_Identifier_Key: 'device_id_inogen_dev',
  LOCATION_DATA: 'location_data',
  PAIRED_DATE_FOR_FILTER: 'paired_date_for_filter',
  PAIRED_DATE_FOR_CANNULA: 'paired_date_for_cannula',
  pocDeviceID: 'pocDeviceID',
  isPaired: 'isPaired',
  isReactApp: 'isReactApp',
  InogenDeviceModel: 'InogenDeviceModel',
  isRemoteFirmwareVersionAvailable: 'isRemoteFirmwareVersionAvailable',
  concentratorProfileData: 'concentratorProfileData',
  HealthCheckRecord: 'HealthCheckRecordEntity',
  ConcentratorNotificationHistory: 'ConcentratorNotificationHistory',
  TermsAndUsage: 'TermsAndUsage',
  concentratorEngineeringValTimer: 'concentratorEngineeringValTimer',
  concentratorEngineeringVals: 'concentratorEngineeringVals',
  DeviceDataRecord: 'DeviceDataRecord',
  InogenDeviceRecord: 'InogenDeviceRecord',
  PassiveDataSentDate: 'PassiveDataSentDate',
  InogenConfigRecord: 'InogenConfigRecord',
  settingResponse: 'settingResponse',
  fcm_token: 'fcmToken',
  lastInitialNotificationID: 'lastInitialNotificationID',
  InogenPatientRecord: 'InogenPatientRecord',
  InogenPatientAction: 'InogenPatientAction',
  PatientProviderRecord: 'PatientProviderRecord',
  FormSubmitted: 'FormSubmitted',
  BLEConnectionHistoryRecord: 'BLEConnectionHistoryRecord',
  AuthenticationTokenRecord: 'AuthenticationTokenRecord',
  ProviderRecord: 'ProviderRecord',
  TermsOfUseSettingsRecord: 'TermsOfUseSettingsRecord',
  languageTranslation: 'LanguageTranslation',
  languageVersion: 'languageVersion',
  validicUserId: 'validicUserId',
  validicMobileToken: 'validicMobileToken',
  validicMarketplaceToken: 'validicMarketplaceToken',
  validicMarketplaceData: 'validicMarketplaceData',
  validicHealthKitEnabled: 'validicHealthKitEnabled',
  validicHealthMetrics: 'validicHealthMetrics',
  ValidicHealthMetricRecords: 'ValidicHealthMetricRecords',
  savedErrorCodeReport: 'savedErrorCodeReport',
  savedErrorRecallReport: 'savedErrorRecallReport',
  validicConfig: 'validicConfig',
  commandIntervalList: 'commandIntervalList',
};

export const CredConstants = {
  ORG_ID: '636d25df39818d0001b428b4',
  TOKEN: '9561bab6cf36e91bde3cdb99820caaca',
  PATIENT_ID: '138',
};
